# Generated by Django 3.1.4 on 2020-12-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='sample_1',
            field=models.DateField(blank=True, null=True, verbose_name='サンプル項目1 日付'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sample_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='サンプル項目2 日付時刻'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sample_3',
            field=models.TimeField(blank=True, null=True, verbose_name='サンプル項目3 日時'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sample_4_end',
            field=models.DateField(blank=True, null=True, verbose_name='サンプル項目4 期間 終了日'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sample_4_start',
            field=models.DateField(blank=True, null=True, verbose_name='サンプル項目4 期間 開始日'),
        ),
    ]
